version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yml:/etc/loki/local-config.yaml
      - loki-index:/loki/index
      - loki-chunks:/loki/chunks
    command: -config.file=/etc/loki/local-config.yaml
    user: "0"

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

volumes:
  grafana-data:
  loki-index:
  loki-chunks:
